name: FSL Challenge Pipe

on:
    pull_request:
        type: [opened, synchronize, reopened]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set Up Node.js v15
              uses: actions/setup-node@v3
              with:
                node-version: '15'

            - name: Set Up NPM v7
              run: npm install -g npm@7

            - name: Install dependencies
              run: cd codebase/rdicidr-0.1.0  && npm install
              
            - name: Linter (ESLint)
              run: cd codebase/rdicidr-0.1.0  && npm run lint

            - name: Formatter (Prettier)
              run: cd codebase/rdicidr-0.1.0  && npm run prettier -- --write

            - name: Test (Jest)
              run: cd codebase/rdicidr-0.1.0  && CI=true npm run test

            - name: Build the application
              run: cd codebase/rdicidr-0.1.0 && npm run build